title:               Hussein Sharadga
url:                 https://hssharadga.github.io/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Hussein Sharadga
  url:               https://hssharadga.github.io/
  email:             hssharadga@utexas.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
